package fr.rayane.repetitionreviewer.constant;

public enum QualityConstant {
  COMPLETE_BLACKOUT,
  INCORRECT_RESPONSE,
  INCORRECT_RESPONSE_EASY_TO_REMEMBER,
  CORRECT_RESPONSE_DIFFICULT_TO_RECALL,
  CORRECT_RESPONSE_AFTER_HESITATION,
  PERFECT_RESPONSE
}
